version: '2'
services:
  apache:
    build: ./docker/apache/.
    image: my_php-5.6-apache:20160303
    volumes:
      - ./src:/var/www/html
      - ./apache-log:/var/log/apache2
    ports:
      - "80:80"
      - "443:443"
    environment:
      APACHE_LOG_DIR: '/var/log/apache2'
    links:
      - db
    working_dir: /var/www/html
  db:
    build: ./docker/mysql/.
    image: my_mysql-5.7:20160303
    volumes:
      - ./docker/mysql/initial-data:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'phpapp'
    ports:
      - "3306:3306"