version: '2'
services:
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile-php
    image: local/php:5.6
    volumes:
      - ./src:/var/www/html
      - ./apache-log:/var/log/apache2
    ports:
      - "80:80"
      - "443:443"
    environment:
      APACHE_LOG_DIR: '/var/log/apache2'
    links:
      - db
    working_dir: /var/www/html
  db:
    image: mysql:5.7
    volumes:
      - ./docker/mysql/initial-data:/docker-entrypoint-initdb.d
      - ./docker/mysql/config:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'db'
    ports:
      - "3306:3306"
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile-node
    image: local/node:5-gulp
    volumes:
      - ./docker/node/data:/var/www/node
    volumes_from:
      - php
    links:
      - php
    ports:
      - "3001:3001"
      - "8080:8080"
    working_dir: /var/www/node