version: '2'
services:
  apache:
    build: ./docker/apache/.
    volumes:
      - ./src:/var/www/html
      - ./apache-log:/var/log/apache2
    ports:
      - "80:80"
      - "443:443"
    environment:
      APACHE_LOG_DIR: '/var/log/apache2'
    links:
      - db
    working_dir: /var/www/html
  db:
    build: ./docker/mysql/.
    volumes:
      - ./docker/mysql/initial-data:/docker-entrypoint-initdb.d
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'phpapp'
    ports:
      - "3306:3306"
  node:
    build: ./docker/node/.
    volumes:
      - ./docker/node/d:/var/www/node
    volumes_from:
      - apache
    links:
      - apache
    ports:
      - "3001:3001"
      - "8080:8080"
    working_dir: /var/www/node