version: '2'
services:
  apache:
    build: .
    image: php-5.6-apache:20160303
    volumes:
      - ./src:/var/www/html
      - ./apache-log:/var/log/apache2
    ports:
      - "80:80"
      - "443:443"
    environment:
      APACHE_LOG_DIR: '/var/log/apache2'
    links:
      - db
    working_dir: /var/www/html
  db:
    image: mysql:5.7
    volumes:
      - ./docker/mysql:/etc/mysql/conf.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'phpapp'
    ports:
      - "3306:3306"