version: '2'
services:
  php:
    build: ./docker/php/
    image: local/php:7
    volumes:
      - ./src/:/var/www/html/
      - ./log/apache/:/var/log/apache2/
      - ./config/php/sites-enabled/:/etc/apache2/sites-enabled/
    ports:
      - 80:80
      - 443:443
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
      - VIRTUAL_HOST=example.local
      - VIRTUAL_HOST_DIRECTORY=/var/www/html
    links:
      - db
      - mailcatcher
    working_dir: /var/www/html/
  db:
    image: percona:5.7
    volumes:
      - ./config/mysql/initial-data/:/docker-entrypoint-initdb.d/
      - ./config/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./data/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
  node:
    build: ./docker/node/
    image: local/node:6-gulp
    volumes_from:
      - php
    links:
      - php
    ports:
      - 3001:3001
      - 8080:8080
    working_dir: /var/www/html/
  ngrok:
    image: wernight/ngrok
    command: ngrok http php:80
    ports:
      - 4040:4040
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080